alertmanager:
  alertmanagerSpec:
    # Selects Alertmanager configuration based on these labels
    alertmanagerConfigSelector:
      matchLabels:
        release: monitoring

    # Set the number of Alertmanager replicas for high availability
    replicas: 2

    # Strategy for matching Alertmanager configurations
    alertmanagerConfigMatcherStrategy:
      type: None

    # Add Alertmanager configuration for email notifications
    alertmanagerConfig:
      global:
        resolve_timeout: 5m
        smtp_smarthost: 'smtp.gmail.com:587'  # Replace with your SMTP server and port
        smtp_from: 'smruti.mohanty@infra360.io'    # Replace with your "from" email address
        smtp_auth_username: 'Smruti Ranjan Mohanty'  # Replace with your email username
        smtp_auth_password: 'Kanhu2001'  # Replace with your email password
        smtp_require_tls: true
      route:
        receiver: 'email-notifications'
        group_by: ['alertname']
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 1h
      receivers:
        - name: 'email-notifications'
          email_configs:
            - to: 'mohantysmrutiranjan001@gmail.com'  # Replace with the recipient's email
              send_resolved: true  # Sends notifications when alerts are resolved
