apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otelcol
  namespace: argocd 
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: HelmCharts/microservices
    repoURL: https://github.com/SmrutiKrishna2001/microservices.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values/otelcol-values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
