{{- if .Values.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Values.statefulset.labels.app }}
spec:
  serviceName: {{ .Release.Name }}
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.statefulset.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulset.labels.app }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.statefulset.containers.image }}
          ports:
          {{- if .Values.statefulset.containers.ports }}
          {{- range .Values.statefulset.containers.ports }}
            - containerPort: {{ .containerPort }}
          {{- end }}
          {{- end }}
          volumeMounts:
          {{- if .Values.statefulset.volumeMounts }}
          {{- range .Values.statefulset.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
          {{- end }}
          {{- end }}
          env:
          {{- if .Values.statefulset.env }}
          {{- range .Values.statefulset.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.statefulset.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.statefulset.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.statefulset.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.statefulset.readinessProbe | nindent 12 }}
          {{- end }}
  volumeClaimTemplates:
  {{- if .Values.statefulset.volumeClaimTemplates }}
  {{- range .Values.statefulset.volumeClaimTemplates }}
    - metadata:
        name: {{ .name }}
      spec:
        accessModes:
        {{- range .accessModes }}
          - {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ .spec.resources.requests.storage }}
        {{- if .storageClassName }}
        storageClassName: {{ .storageClassName }}
        {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
