# prometheus-rules.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cpu-hike-alert
  namespace: monitoring  # Change if needed
spec:
  groups:
  - name: cpu-alerts
    rules:
    - alert: HighCpuUsage
      expr: sum(rate(container_cpu_usage_seconds_total{container!="", container!="POD", job="kubelet", namespace="monitoring"}[5m])) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{container!="", container!="POD", namespace="monitoring"}) by (pod) * 100 > 70
      for: 1m
      labels:
        severity: critical
      annotations:
        description: "CPU usage for pod {{ $labels.pod }} is over 70%"  # Correct usage of $labels
        summary: "CPU usage of pod {{ $labels.pod }} is above 70%"      # Correct usage of $labels
