apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prom-sc  # Custom name for StorageClass
provisioner: ebs.csi.aws.com
parameters:
  type: gp3  # Volume type, change to gp2, io1, etc. based on your needs
reclaimPolicy: Retain  # Ensure data is not deleted when PVC is deleted
volumeBindingMode: WaitForFirstConsumer  # Delayed binding until a pod is scheduled
